name: main_app
description: A new Flutter project.

publish_to: "none" #

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  #StateManagement & DI
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #FP
  fpdart: ^0.4.1
  rxdart: ^0.27.7
  dartz: ^0.10.1
  equatable: ^2.0.5

  #Apis
  dio: ^5.0.1
  chopper: ^6.1.1
  native_flutter_proxy: ^0.1.15

  #LocalStorage
  flutter_secure_storage: ^8.0.0

  #Images
  cached_network_image: ^3.2.0
  lottie: ^1.2.1

  #Utils
  mocktail: ^0.3.0
  fast_immutable_collections: ^8.1.0
  url_launcher: ^6.0.20

  #Navigation
  go_router: ^6.2.0

  melos: ^2.9.0
  flutter_flavor: ^3.1.1

  #Connectivity
  connectivity_plus: ^3.0.2

  #Analytics
  datadog_flutter_plugin: ^1.2.1
  stack_trace: ^1.10.0
  flutter_jailbreak_detection: ^1.10.0

  #UI
  flutter_screenutil: ^5.6.1
  very_good_infinite_list: ^0.7.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  riverpod_generator: ^1.2.0
  riverpod_lint:

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
