name: main_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  #StateManagement & DI
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #FP
  fpdart: ^0.4.1
  rxdart: ^0.27.7
  dartz: ^0.10.1
  equatable: ^2.0.5

  #Apis
  dio: ^4.0.4

  #LocalStorage
  shared_preferences: ^2.0.17
  sqflite: ^2.0.1
  flutter_cache_manager: ^3.3.0
  image_picker: ^0.8.4+4

  #Images
  cached_network_image: ^3.2.0
  lottie: ^1.2.1


  #Utils
  mocktail: ^0.3.0
  fast_immutable_collections: ^8.1.0
  flutter_fadein: ^2.0.0
  uuid: ^3.0.5
  url_launcher: ^6.0.20

  #Navigation
  go_router: ^6.0.6


  melos: ^2.9.0
  flutter_flavor: ^3.1.1

  #Connectivity
  connectivity_plus: ^3.0.2

  datadog_flutter_plugin: ^1.2.1
  stack_trace: ^1.10.0
  flutter_screenutil: ^5.6.1
  flutter_jailbreak_detection: ^1.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  riverpod_generator: ^1.2.0
  riverpod_lint:
  custom_lint:
  go_router_builder: ^1.0.15

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
